### ISSUE TITLE
Updating to .NET 4.5 (and ditch the AsyncTargetingPack.Net4)

### ISSUE THREAD

**Issue by MrBasque** [destiny14/YahooWeatherNET#3]
Hi @destiny14, thanks for your wonderful component!

I was trying to use it in a Xamarin project (with Xamarin Studio on a Mac), where the component was used in the shared PCL. Building and running on IOS without problems, though on android It would not build. (complaining about missing system.servicemodel.discovery which is not available in mono )

Anyhow, I decided to remove the Microsoft.CompilerServices.AsyncTargetingPack.Net4 reference and converted the project to .net 4.5. This seems to solve the entire problem and everythingn seems to run fine.

Any particular reason I should not to upgrade to 4.5? 

pull-request: #4

**Comment by destiny14** [comment]
Hey @MrBasque ,

the AsyncTargetingPack and the lower Framework version were essentially just a leftover from the times when this library wasn't Open Source. Thank you for your pull request, I'll merge it now.
